export const listOfblogs = [
  {
    id: 1,
    title: 'judul',
    desc: 'deskripsi',
    url: 'sukses',
    likes: 8,
  },
  {
    id: 2,
    title: 'judul',
    desc: 'deskripsi',
    url: 'lancar',
    likes: 19,
  },
  {
    id: 3,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki',
    likes: 27,
  },
  {
    id: 4,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki 1',
    likes: 14,
  },
  {
    id: 5,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki 2',
    likes: 11,
  },
  {
    id: 6,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki 3',
    likes: 11,
  },
  {
    id: 7,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki 4',
    likes: 11,
  },
  {
    id: 8,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki 5',
    likes: 11,
  },
  {
    id: 9,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki 6',
    likes: 11,
  },
  {
    id: 10,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki 7',
    likes: 11,
  },
  {
    id: 11,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki 8',
    likes: 11,
  },
  {
    id: 12,
    title: 'judul',
    desc: 'deskripsi',
    url: 'rejeki 9',
    likes: 11,
  },
];

export const workProjects = [
  {
    id: 1,
    title: 'Beacon',
    description: 'A beautiful Linear portal for clients',
    techStack: ['React', 'TypeScript', 'Tailwind'],
    mediaUrl: '/images/beacon-preview.png',
    mediaType: 'image' as const,
    category: 'Brand / Product / Growth',
  },
  {
    id: 2,
    title: 'Antigravity A1',
    description: 'Next-gen drone technology',
    techStack: ['Three.js', 'WebGL', 'Node.js'],
    mediaUrl: '/images/antigravity-preview.jpg',
    mediaType: 'image' as const,
    category: 'Product / Growth',
  },
  {
    id: 3,
    title: 'Rayzen',
    description: 'Modern design system',
    techStack: ['TypeScript', 'Tauri', 'SolidJS', 'Rust'],
    canvasColors: [
      [255, 99, 71],
      [255, 140, 0],
    ],
    category: 'Brand',
  },
];
