/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as LayoutWidgetIdRouteImport } from './routes/_layout.$widgetId'
import { Route as LayoutWidgetIdIndexRouteImport } from './routes/_layout.$widgetId.index'
import { Route as LayoutWidgetIdContentIdRouteImport } from './routes/_layout.$widgetId.$contentId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWidgetIdRoute = LayoutWidgetIdRouteImport.update({
  id: '/$widgetId',
  path: '/$widgetId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWidgetIdIndexRoute = LayoutWidgetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutWidgetIdRoute,
} as any)
const LayoutWidgetIdContentIdRoute = LayoutWidgetIdContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => LayoutWidgetIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$widgetId': typeof LayoutWidgetIdRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/': typeof LayoutIndexRoute
  '/$widgetId/$contentId': typeof LayoutWidgetIdContentIdRoute
  '/$widgetId/': typeof LayoutWidgetIdIndexRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/': typeof LayoutIndexRoute
  '/$widgetId/$contentId': typeof LayoutWidgetIdContentIdRoute
  '/$widgetId': typeof LayoutWidgetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/$widgetId': typeof LayoutWidgetIdRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$widgetId/$contentId': typeof LayoutWidgetIdContentIdRoute
  '/_layout/$widgetId/': typeof LayoutWidgetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$widgetId'
    | '/api/$'
    | '/'
    | '/$widgetId/$contentId'
    | '/$widgetId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/$' | '/' | '/$widgetId/$contentId' | '/$widgetId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/$widgetId'
    | '/api/$'
    | '/_layout/'
    | '/_layout/$widgetId/$contentId'
    | '/_layout/$widgetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/$widgetId': {
      id: '/_layout/$widgetId'
      path: '/$widgetId'
      fullPath: '/$widgetId'
      preLoaderRoute: typeof LayoutWidgetIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$widgetId/': {
      id: '/_layout/$widgetId/'
      path: '/'
      fullPath: '/$widgetId/'
      preLoaderRoute: typeof LayoutWidgetIdIndexRouteImport
      parentRoute: typeof LayoutWidgetIdRoute
    }
    '/_layout/$widgetId/$contentId': {
      id: '/_layout/$widgetId/$contentId'
      path: '/$contentId'
      fullPath: '/$widgetId/$contentId'
      preLoaderRoute: typeof LayoutWidgetIdContentIdRouteImport
      parentRoute: typeof LayoutWidgetIdRoute
    }
  }
}

interface LayoutWidgetIdRouteChildren {
  LayoutWidgetIdContentIdRoute: typeof LayoutWidgetIdContentIdRoute
  LayoutWidgetIdIndexRoute: typeof LayoutWidgetIdIndexRoute
}

const LayoutWidgetIdRouteChildren: LayoutWidgetIdRouteChildren = {
  LayoutWidgetIdContentIdRoute: LayoutWidgetIdContentIdRoute,
  LayoutWidgetIdIndexRoute: LayoutWidgetIdIndexRoute,
}

const LayoutWidgetIdRouteWithChildren = LayoutWidgetIdRoute._addFileChildren(
  LayoutWidgetIdRouteChildren,
)

interface LayoutRouteChildren {
  LayoutWidgetIdRoute: typeof LayoutWidgetIdRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutWidgetIdRoute: LayoutWidgetIdRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
